services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: siyaqi_db
      POSTGRES_USER: siyaqi
      POSTGRES_PASSWORD: siyaqi_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
